version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: jpa-hibernate-book
    environment:
      POSTGRES_DB: jpa-hibernate-book
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
